ALTER TABLE "category" ALTER COLUMN "companyName" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "category" ALTER COLUMN "name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "category" ALTER COLUMN "description" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "category" ALTER COLUMN "image" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "companyWebsite" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "brandName" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "headLine" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "subHeadLine" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "heroImage" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "headLineFontSize" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "subHeadLineFontSize" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "email" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "phone" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "address" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "facebook" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "instagram" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "youtube" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "company" ALTER COLUMN "createdAt" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "faq" ALTER COLUMN "companyName" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "faq" ALTER COLUMN "question" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "faq" ALTER COLUMN "answer" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "lastView" ALTER COLUMN "companyName" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "companyName" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "productName" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "productDescription" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "productLink" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "price" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "category" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "inventory" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "reviews" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "review" ALTER COLUMN "companyName" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "review" ALTER COLUMN "name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "review" ALTER COLUMN "review" DROP NOT NULL;